// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKz3RO3DGaAzrR9Z3KmQ_450hbnvdYtqY',
    appId: '1:637763517736:web:76fb57d0adfd0c24b1241d',
    messagingSenderId: '637763517736',
    projectId: 'everyday-a3a63',
    authDomain: 'everyday-a3a63.firebaseapp.com',
    storageBucket: 'everyday-a3a63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAILO9fwl5X-1RPpHiX5nQCsuNnWuK685M',
    appId: '1:637763517736:android:998b94a4e7cee241b1241d',
    messagingSenderId: '637763517736',
    projectId: 'everyday-a3a63',
    storageBucket: 'everyday-a3a63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-M5X5OSHgzsc66axsWmvrdlByJwUnkYE',
    appId: '1:637763517736:ios:1ffd914dbdde81afb1241d',
    messagingSenderId: '637763517736',
    projectId: 'everyday-a3a63',
    storageBucket: 'everyday-a3a63.appspot.com',
    iosClientId: '637763517736-tjfnq3p5tp1tlou3607qhbs6pbfr7d4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.everyday',
  );

}